### ISSUE TITLE
Doesn't work on Ubuntu 19.04

### ISSUE THREAD

**Issue by gurchk** [jsnjack/time-tracker#11]
Hey the program is not able to open, nothing happends if you click the time in the taskbar.

**Comment by jsnjack** [comment]
Hi! Strange, I have just verified that it works in gnome 3.34 :) Could you please share some tracebacks? What Gnome version do you use?

**Comment by gurchk** [comment]
Hello, i use gnome 3.32.1 The actual time tracking works but the click listener in the taskbar doesn't fire.  
Not sure what else i could provide you.
Thanks

**Comment by gurchk** [comment]
It magically started working once i restarted my computer and reinstalled everything. Thanks
