### ISSUE TITLE
First click in ‘Adjust pause duration’ changes time tracked to seemingly random value

### ISSUE THREAD

**Issue by vhennebert** [jsnjack/time-tracker#12]
GNOME 3.36 (but observed the same behaviour on GNOME 3.34)

- Start the timer
- Go to preferences
- Click on any of the +/− buttons in the Adjust pause duration section

The time elapsed suddenly changes to some (usually high) random value. After the first click it then starts working expectedly, adding/subtracting one hour/min at a time.

Example: I have 22:10 tracked so far. I want to adjust it to 21:50 (been procrastinating…). I click on any of the +/− buttons, it suddenly jumps to 57:12 or something. I have to do some mental calculation to enter 35 hours and 22 minutes in the fields to bring it down to 21:50.

Mind you, mental calculation is good to keep the brain sharp. But I guess I could do without it :)

Thanks for this great, simple extension.

**Comment by jsnjack** [comment]
> Mind you, mental calculation is good to keep the brain sharp. But I guess I could do without it :)

Haha fair point!

I've just tried to reproduce the issue on GNOME 3.38 and wasn't able to. I don't really have other GNOME versions installed, but I don't remember seeing this issue in any of them. I wonder if it could depend on the language / formatsettings... Which ones do you have? (English - UK for me)

**Comment by vhennebert** [comment]
Hmmm. I use English UK as well as language and format. Not sure what’s going on.

One thing I noticed is that the correction I must apply seems to always be the same between two pauses.

Example: I start the timer, pause it, restart it. While it’s running, I want to adjust the pause duration. I click on the + button for the minutes, it jumps to some random value. I have to set the duration to, say 22h and 5min to get the time back to its original value. Until I pause the timer again, I will always have to apply that 22h and 5min correction to re-adjust the timer after tweaking the pause duration.

Now I pause my timer. After a while I restart it. Until the next pause, the correction I’ll have to apply will always be, say, 50h and 12min.

Does that give any hint as to what might be going wrong?

**Comment by jsnjack** [comment]
I think I have found the issue. I couldn't reproduce exactly what you mentioned, but it looks like it could be the reason.

If the issue still exists, could you please create a video and also monitor with `dconf` this section `/org/gnome/shell/extensions/time-tracker/`? :)

**Comment by vhennebert** [comment]
Sorry for the delay, been offline for the past two weeks.
Now the first click on an adjustment button works, but following clicks don’t. I tried to describe it in the attached screencast, please let me know if you have any questions or would like me to try anything else. (Sorry for the few seconds freeze around 1:21, I was running heavy stuff in the background)

https://user-images.githubusercontent.com/1881842/106628621-47cd8980-657a-11eb-8323-63e1443eccfb.mp4

**Comment by jsnjack** [comment]
Ah I see what you mean! Thanks for the video :) I will release the fix soon

**Comment by jsnjack** [comment]
@vhennebert should be fixed now :)

**Comment by vhennebert** [comment]
So I’ve been running the updated extension for a few days now and it’s behaving as expected. Considering it fixed. Thanks! This great little extension has become even better :)

**Comment by jsnjack** [comment]
Absolutely! Thanks for the bug report and the detailed description
