### ISSUE TITLE
Support for Gnome 40

### ISSUE THREAD

**Issue by sisou** [jsnjack/time-tracker#13]
Hello!
I was using this extension on Fedora 33, but now I updated to 34, which uses Gnome 40.

Are there any plans to update this extension to work in Gnome 40?
https://gjs.guide/extensions/upgrading/gnome-shell-40.html#contents

I had a look into the guide myself, but I have never worked with GTK or Gnome and have no idea what I should be doing.

I also tried to just "fake" compatibility with the existing code (adding `"40"` to the `metadata.json` shell-version array), but all that works is displaying the timer in the top-bar. When clicking it, nothing happens (the notification doesn't open), and as expected the preferences dialog also doesn't open (must be ported to Gtk4).

**Comment by jsnjack** [comment]
Thanks for the guide! I'll look into it at some point, hope it is not too many changes!
