### ISSUE TITLE
Label colors settings

### ISSUE THREAD

**Issue by zagortenay333** [jsnjack/time-tracker#3]
Would it be possible to add the option to change the color of  the label in the settings? Since themes cannot override the extension stylesheets, this can be an issue on a lot of themes

**Comment by jsnjack** [comment]
Well that is a good point. I will look into it.

**Comment by jsnjack** [comment]
@zagortenay333 updated version can be expected in a day or so on the gnome shell extensions website

**Comment by zagortenay333** [comment]
Nice :smile:
