### ISSUE TITLE
Break time

### ISSUE THREAD

**Issue by beatgammit** [jsnjack/time-tracker#4]
I'm using this to track my work hours and it works pretty well. However, when I take a break (like lunch), I sometimes forget to unpause the timer. I can usually remember what time I finished lunch, but there's no way to adjust it so I just have to remember when I enter my hours at the end of the day.

I would like to see the following features:

- log of how long the timer has been paused since the start
  - bonus points if each break has start/end times as well
- manually add/subtract time from counter (through preferences)
  - sometimes I forget to stop the timer, sometimes I forget to start it

Thoughts?

**Comment by jsnjack** [comment]
You can change counter time by adjusting start time in the preference (that how I do it now when I forget to reset/unpause).

I like the idea about pause duration. I will implement it soon.

**Comment by beatgammit** [comment]
Awesome! I wasn't sure how much you wanted to put into this. I like the simplicity so far.

Adjusting the start time works; I was just hoping for something a little more fine-grained (so I can still have my actual start time). Again, I like the simplicity of it now, so I'm totally fine with not adding another field if you're hesitant.

**Comment by jsnjack** [comment]
I added an option to edit pause time. New version is being reviewed by gnome team, should be available soon.
