### ISSUE TITLE
Unable to restart or pause due to possible Pomodoro notification blocking

### ISSUE THREAD

**Issue by octoquad** [jsnjack/time-tracker#5]
Hi,

Thank you for making this extension! I've come across this problem before using Ubuntu GNOME 15.04 with Gnome Shell 3.14 and 3.16 but over time it seems to have fixed itself.

I recently upgraded to Ubuntu 15.10 today and noticed that if a Pomodoro timer is running, the options to restart or pause Time Tracker do not show up, but rather get stacked in the notification area. If you switch off the Pomodoro timer, it works again and you can restart and pause time tracker.

**Steps to Reproduce**
1. Install the gnome-shell-pomodoro package.
2. Install the time-tracker package from extensions.gnome.org
3. Restart the shell
4. Start a Pomodoro Timer
5. Click on Time Tracker
6. Time Tracker notifications get stacked in notification area

Pomodoro Enabled
![1 stacking - pomodoro timer enabled](https://cloud.githubusercontent.com/assets/1165755/10281802/4a6104fe-6b77-11e5-9aed-cd665a0af747.png)

Pomodoro Disabled
![2 normal - pomodoro timer disable](https://cloud.githubusercontent.com/assets/1165755/10281805/4d021dd8-6b77-11e5-8b72-33b60064a07f.png)

If you need any other information, please let me know.

Thanks

**Comment by jsnjack** [comment]
Hello,

Pomodoro extension by default hides all notifications. If you disable this option (see pic) you will have time-tracker buttons back 
![screenshot from 2015-10-05 23-51-01](https://cloud.githubusercontent.com/assets/5493713/10294897/4fca716e-6bbd-11e5-9c86-e8ed2dd23a77.png)

**Comment by octoquad** [comment]
@jsnjack Thanks, totally forgot about that option in Pomodoro!

**Comment by jsnjack** [comment]
@octoquad happy to help! :)
