### ISSUE TITLE
Improving the panel icon

### ISSUE THREAD

**Issue by zagortenay333** [jsnjack/time-tracker#7]
The time in the panel doesn't behave like the other items. It has no hover effect and has an odd padding.

Would be also cool if could be set to show only an icon.

**Comment by jsnjack** [comment]
@zagortenay333 thank you for reporting the issue. What do you mean by odd padding (could you please provide a screenshot?)? I use default gnome theme and the padding looks good. I also do not use any custom styles for the widget, so it should look ok (unless some standard class is missing).

**Comment by zagortenay333** [comment]
It should have the class `.panel-button`.

![screenshot from 2016-07-26 20-43-44](https://cloud.githubusercontent.com/assets/11144630/17150957/c8fc3a30-5371-11e6-87e0-f0b547e60418.png)
