### ISSUE TITLE
Click + modifiers for start,pause,reset

### ISSUE THREAD

**Issue by lweberk** [jsnjack/time-tracker#8]
Hi,

would love to have a way to start, pause and reset without having to click on the timer, then on the notification window buttons but directly on the timer itself. Maybe with left click; start/pause and right click reset?

Best regards,
~lwk

**Comment by lweberk** [comment]
Digged around in clutter and there is no easy way of doing this. The only event found so far, was button pressing, which is triggered on both left and right clicks.

There is also the problem of conflicting with the preferences popup.

**Comment by jsnjack** [comment]
True. Looks like it won't improve user expierence :(

**Comment by lweberk** [comment]
Possibly a context menue directly from the timer down?

**Comment by lweberk** [comment]
Regardless it misses the issues description. Closing...
